"""add deep fingerprinting fields

Revision ID: 32778a26a08c
Revises: 3d2fe6c56acc
Create Date: 2026-06-25 22:24:11.320274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32778a26a08c'
down_revision: Union[str, None] = '3d2fe6c56acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_visits', sa.Column('viewport_width', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('viewport_height', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('pixel_ratio', sa.Float(), nullable=True))
    op.add_column('page_visits', sa.Column('color_depth', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('cpu_cores', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('device_memory', sa.Float(), nullable=True))
    op.add_column('page_visits', sa.Column('max_touch_points', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('gpu_renderer', sa.String(length=255), nullable=True))
    op.add_column('page_visits', sa.Column('connection_type', sa.String(length=50), nullable=True))
    op.add_column('page_visits', sa.Column('downlink_speed', sa.Float(), nullable=True))
    op.add_column('page_visits', sa.Column('cookies_enabled', sa.Boolean(), nullable=True))
    op.add_column('page_visits', sa.Column('do_not_track', sa.Boolean(), nullable=True))
    op.add_column('page_visits', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    op.add_column('page_visits', sa.Column('reduced_motion', sa.Boolean(), nullable=True))
    op.add_column('page_visits', sa.Column('pdf_viewer', sa.Boolean(), nullable=True))
    op.add_column('page_visits', sa.Column('plugins_count', sa.Integer(), nullable=True))
    op.add_column('page_visits', sa.Column('languages', sa.String(length=255), nullable=True))
    op.add_column('page_visits', sa.Column('canvas_hash', sa.String(length=64), nullable=True))
    op.add_column('page_visits', sa.Column('webgl_hash', sa.String(length=64), nullable=True))
    op.add_column('page_visits', sa.Column('battery_level', sa.Float(), nullable=True))
    op.add_column('page_visits', sa.Column('battery_charging', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_visits', 'battery_charging')
    op.drop_column('page_visits', 'battery_level')
    op.drop_column('page_visits', 'webgl_hash')
    op.drop_column('page_visits', 'canvas_hash')
    op.drop_column('page_visits', 'languages')
    op.drop_column('page_visits', 'plugins_count')
    op.drop_column('page_visits', 'pdf_viewer')
    op.drop_column('page_visits', 'reduced_motion')
    op.drop_column('page_visits', 'dark_mode')
    op.drop_column('page_visits', 'do_not_track')
    op.drop_column('page_visits', 'cookies_enabled')
    op.drop_column('page_visits', 'downlink_speed')
    op.drop_column('page_visits', 'connection_type')
    op.drop_column('page_visits', 'gpu_renderer')
    op.drop_column('page_visits', 'max_touch_points')
    op.drop_column('page_visits', 'device_memory')
    op.drop_column('page_visits', 'cpu_cores')
    op.drop_column('page_visits', 'color_depth')
    op.drop_column('page_visits', 'pixel_ratio')
    op.drop_column('page_visits', 'viewport_height')
    op.drop_column('page_visits', 'viewport_width')
    # ### end Alembic commands ###
