# =========================================================
#  QUIZ TÍNH CÁCH TRIẾT HỌC — MLN111
#  110 câu (10 câu/triết lý) — q001..q110
# =========================================================

QUESTIONS = [

    # ---------- DUY VẬT (materialism) — q001..q010 ----------
    {
        "code": "q001",
        "section": "work_discipline",
        "text": "Muốn học hành nên hồn thì trước hết phải lo đủ ăn, đủ ngủ và có chỗ học tử tế; 'quyết tâm' suông thôi thì khó bền.",
        "order_index": 1,
        "illustration_key": "deadline_monster",
        "weights": {"materialism": 2},
    },
    {
        "code": "q002",
        "section": "ethics_society",
        "text": "Con người sống trong hoàn cảnh nào thì dần hình thành lối nghĩ nấy — môi trường nặn ra tính cách, không tự nhiên mà có.",
        "order_index": 2,
        "illustration_key": "society_pyramid",
        "weights": {"materialism": 2},
    },
    {
        "code": "q003",
        "section": "meaning_life",
        "text": "Trước khi bàn chuyện lý tưởng cao xa, mình muốn xem cơm áo gạo tiền của mình đang thế nào đã.",
        "order_index": 3,
        "illustration_key": "cartoon_philosopher",
        "weights": {"materialism": 2},
    },
    {
        "code": "q004",
        "section": "work_discipline",
        "text": "Khi lập kế hoạch, mình bắt đầu từ nguồn lực thực tế đang có (tiền, thời gian, sức khỏe) chứ không từ mơ ước.",
        "order_index": 4,
        "illustration_key": "deadline_monster",
        "weights": {"materialism": 2, "pragmatism": 1},
    },
    {
        "code": "q005",
        "section": "emotions_conflict",
        "text": "Tâm trạng mình lên xuống phần lớn do những thứ rất vật chất: đói, thiếu ngủ, hết tiền — chứ ít khi do 'vũ trụ'.",
        "order_index": 5,
        "illustration_key": "cartoon_philosopher",
        "weights": {"materialism": 2},
    },
    {
        "code": "q006",
        "section": "meaning_life",
        "text": "Mình tin đổi đời phải bắt đầu từ thay đổi điều kiện sống thật, chứ chỉ 'nghĩ tích cực' thôi thì chưa đủ.",
        "order_index": 6,
        "illustration_key": "society_pyramid",
        "weights": {"materialism": 2},
    },
    {
        "code": "q007",
        "section": "ethics_society",
        "text": "Muốn hiểu vì sao xã hội thế này, mình nhìn vào ai đang nắm của cải và điều kiện kinh tế trước tiên.",
        "order_index": 7,
        "illustration_key": "society_pyramid",
        "weights": {"materialism": 2},
    },
    {
        "code": "q008",
        "section": "work_discipline",
        "text": "Mình theo kiểu 'có thực mới vực được đạo' — lo ổn phần vật chất rồi mới tính chuyện tinh thần.",
        "order_index": 8,
        "illustration_key": "deadline_monster",
        "weights": {"materialism": 2},
    },
    {
        "code": "q009",
        "section": "emotions_conflict",
        "text": "Với mình, thực tế khách quan vẫn diễn ra theo quy luật của nó, dù mình có tin hay mong muốn thế nào đi nữa.",
        "order_index": 9,
        "illustration_key": "cartoon_philosopher",
        "weights": {"materialism": 2},
    },
    {
        "code": "q010",
        "section": "meaning_life",
        "text": "Suy nghĩ của mình suy cho cùng là phản ánh của thế giới vật chất bên ngoài, chứ không có sẵn từ trong đầu.",
        "order_index": 10,
        "illustration_key": "cartoon_philosopher",
        "weights": {"materialism": 2},
    },

    # ---------- DUY TÂM (idealism) — q011..q020 ----------
    {
        "code": "q011",
        "section": "work_discipline",
        "text": "Mình tin ý chí và niềm tin đủ mạnh có thể vượt qua cả những hoàn cảnh khó khăn nhất.",
        "order_index": 11,
        "illustration_key": "deadline_monster",
        "weights": {"idealism": 2},
    },
    {
        "code": "q012",
        "section": "meaning_life",
        "text": "Một lý tưởng đẹp vẫn đáng để mình theo đuổi, kể cả khi nó chưa mang lại lợi ích thực tế nào.",
        "order_index": 12,
        "illustration_key": "cartoon_philosopher",
        "weights": {"idealism": 2},
    },
    {
        "code": "q013",
        "section": "emotions_conflict",
        "text": "Mình tin nếu tâm mình đủ sáng và ý chí đủ mạnh, hoàn cảnh bên ngoài rồi cũng dần chuyển theo.",
        "order_index": 13,
        "illustration_key": "cartoon_philosopher",
        "weights": {"idealism": 2},
    },
    {
        "code": "q014",
        "section": "ethics_society",
        "text": "Với mình, giá trị tinh thần và đạo lý mới là cái gốc định hình xã hội, chứ không phải điều kiện kinh tế.",
        "order_index": 14,
        "illustration_key": "society_pyramid",
        "weights": {"idealism": 2},
    },
    {
        "code": "q015",
        "section": "meaning_life",
        "text": "Mình tin chính ý thức, tinh thần con người mới là cái có trước và quyết định thế giới quanh ta.",
        "order_index": 15,
        "illustration_key": "cartoon_philosopher",
        "weights": {"idealism": 2},
    },
    {
        "code": "q016",
        "section": "work_discipline",
        "text": "Mình làm việc vì một tầm nhìn trong đầu, và tin tầm nhìn đó sẽ thành hiện thực nếu mình giữ vững nó.",
        "order_index": 16,
        "illustration_key": "deadline_monster",
        "weights": {"idealism": 2},
    },
    {
        "code": "q017",
        "section": "emotions_conflict",
        "text": "Khi buồn, mình tin sức mạnh nội tâm và suy nghĩ tích cực có thể thật sự thay đổi được thực tại của mình.",
        "order_index": 17,
        "illustration_key": "cartoon_philosopher",
        "weights": {"idealism": 2},
    },
    {
        "code": "q018",
        "section": "ethics_society",
        "text": "Với mình, những giá trị cao đẹp như lòng tốt, danh dự quan trọng hơn mọi tính toán vật chất.",
        "order_index": 18,
        "illustration_key": "cartoon_philosopher",
        "weights": {"idealism": 2, "humanism": 1},
    },
    {
        "code": "q019",
        "section": "meaning_life",
        "text": "Mình tin mỗi người sinh ra đã mang sẵn một sứ mệnh tinh thần cần khám phá và sống theo.",
        "order_index": 19,
        "illustration_key": "meaning_void",
        "weights": {"idealism": 2},
    },
    {
        "code": "q020",
        "section": "work_discipline",
        "text": "Mình tin khi mình thật sự khao khát điều gì, cả vũ trụ như hợp sức giúp mình đạt được nó.",
        "order_index": 20,
        "illustration_key": "cartoon_philosopher",
        "weights": {"idealism": 2},
    },

    # ---------- THỰC DỤNG (pragmatism) — q021..q030 ----------
    {
        "code": "q021",
        "section": "work_discipline",
        "text": "Với mình, cái gì chạy được, ra kết quả thì là đúng — lý thuyết hay ho mà vô dụng thì mình bỏ.",
        "order_index": 21,
        "illustration_key": "deadline_monster",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q022",
        "section": "work_discipline",
        "text": "Mình thích cứ thử trước, sai đâu sửa đó, chứ không ngồi chờ kế hoạch hoàn hảo mới chịu bắt đầu.",
        "order_index": 22,
        "illustration_key": "deadline_monster",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q023",
        "section": "meaning_life",
        "text": "Chân lý với mình không phải thứ trừu tượng — cái gì giúp cuộc sống tốt lên thật thì mình mới tin.",
        "order_index": 23,
        "illustration_key": "cartoon_philosopher",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q024",
        "section": "ethics_society",
        "text": "Một quy tắc xã hội chỉ đáng giữ khi nó thật sự có ích; hết hiệu quả thì nên sửa hoặc bỏ.",
        "order_index": 24,
        "illustration_key": "society_pyramid",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q025",
        "section": "emotions_conflict",
        "text": "Khi mâu thuẫn với ai, mình tập trung tìm giải pháp cho ra kết quả, không sa đà tranh cãi ai đúng về lý.",
        "order_index": 25,
        "illustration_key": "cartoon_philosopher",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q026",
        "section": "work_discipline",
        "text": "Mình đánh giá một lời khuyên bằng cách áp dụng thử xem có hiệu quả không, chứ không vì nghe cho hay.",
        "order_index": 26,
        "illustration_key": "deadline_monster",
        "weights": {"pragmatism": 2, "materialism": 1},
    },
    {
        "code": "q027",
        "section": "meaning_life",
        "text": "Mình không quá bận tâm 'ý nghĩa tối thượng', miễn việc mình làm mang lại kết quả cụ thể là đủ.",
        "order_index": 27,
        "illustration_key": "cartoon_philosopher",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q028",
        "section": "emotions_conflict",
        "text": "Buồn hay vui gì thì mình vẫn hỏi: giờ làm gì cho tình hình khá hơn được? — rồi bắt tay làm luôn.",
        "order_index": 28,
        "illustration_key": "chill_cloud",
        "weights": {"pragmatism": 2, "stoicism": 1},
    },
    {
        "code": "q029",
        "section": "ethics_society",
        "text": "Chính sách tốt hay không, cứ nhìn vào kết quả thực tế nó tạo ra cho dân, đừng nhìn khẩu hiệu.",
        "order_index": 29,
        "illustration_key": "society_pyramid",
        "weights": {"pragmatism": 2},
    },
    {
        "code": "q030",
        "section": "work_discipline",
        "text": "Mình sẵn sàng đổi phương pháp liên tục miễn là đạt được mục tiêu, không cứng nhắc bám một cách làm.",
        "order_index": 30,
        "illustration_key": "deadline_monster",
        "weights": {"pragmatism": 2},
    },

    # ---------- KHẮC KỈ (stoicism) — q031..q040 ----------
    {
        "code": "q031",
        "section": "emotions_conflict",
        "text": "Khi mọi thứ rối tung, mình tự hỏi: 'Phần nào mình còn kiểm soát được?' rồi chỉ tập trung vào đúng phần đó.",
        "order_index": 31,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2, "pragmatism": 1},
    },
    {
        "code": "q032",
        "section": "work_discipline",
        "text": "Mình tin kỷ luật bản thân quan trọng hơn cảm hứng — cứ làm đúng giờ, đúng việc dù không thích.",
        "order_index": 32,
        "illustration_key": "deadline_monster",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q033",
        "section": "emotions_conflict",
        "text": "Mình luyện cho cái đầu lạnh: chuyện ngoài tầm tay thì thôi khỏi lo, hơi đâu mà bực mình.",
        "order_index": 33,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q034",
        "section": "work_discipline",
        "text": "Mình chấp nhận chịu khổ trước, hưởng sau — nhịn cái sướng trước mắt để đạt mục tiêu lớn hơn.",
        "order_index": 34,
        "illustration_key": "deadline_monster",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q035",
        "section": "meaning_life",
        "text": "Với mình, sống có ý nghĩa là sống theo lý trí và đức hạnh, chứ không phải chạy theo cảm giác dễ chịu.",
        "order_index": 35,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q036",
        "section": "emotions_conflict",
        "text": "Khi tức giận, mình cố dừng lại để lý trí lên tiếng trước, không để cảm xúc kéo mình đi.",
        "order_index": 36,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q037",
        "section": "work_discipline",
        "text": "Mình xem khó khăn, áp lực là dịp để rèn bản thân cứng cáp hơn, chứ không phải điều cần né tránh.",
        "order_index": 37,
        "illustration_key": "deadline_monster",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q038",
        "section": "ethics_society",
        "text": "Mình không để lời khen chê của người khác điều khiển tâm trạng — bình thản với cả được lẫn mất.",
        "order_index": 38,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q039",
        "section": "meaning_life",
        "text": "Mình tập chấp nhận những gì không thể đổi, và dồn sức vào đúng những điều mình thực sự làm chủ được.",
        "order_index": 39,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2},
    },
    {
        "code": "q040",
        "section": "emotions_conflict",
        "text": "Mình thấy làm chủ được ham muốn của bản thân còn đáng tự hào hơn là thỏa mãn được chúng.",
        "order_index": 40,
        "illustration_key": "cartoon_philosopher",
        "weights": {"stoicism": 2},
    },

    # ---------- HƯỞNG LẠC TIẾT ĐỘ (epicureanism) — q041..q050 ----------
    {
        "code": "q041",
        "section": "emotions_conflict",
        "text": "Mình tin sống là để tận hưởng những niềm vui giản dị: bữa ăn ngon, giấc ngủ đủ, bạn bè quây quần.",
        "order_index": 41,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q042",
        "section": "work_discipline",
        "text": "Mình không ép bản thân khổ sở vì công việc — cân bằng và thoải mái với mình quan trọng hơn thành tích.",
        "order_index": 42,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q043",
        "section": "meaning_life",
        "text": "Với mình, một cuộc đời tốt là cuộc đời ít lo âu, nhiều bình yên, tránh xa đau khổ không cần thiết.",
        "order_index": 43,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q044",
        "section": "emotions_conflict",
        "text": "Khi căng thẳng, mình cho phép mình nghỉ ngơi, chiều bản thân một chút cho dễ chịu trở lại.",
        "order_index": 44,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q045",
        "section": "ethics_society",
        "text": "Mình quý những mối quan hệ bạn bè ấm áp hơn là địa vị hay những thành tựu to tát.",
        "order_index": 45,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2, "humanism": 1},
    },
    {
        "code": "q046",
        "section": "work_discipline",
        "text": "Mình chọn công việc đủ sống mà nhẹ đầu, hơn là việc lương cao nhưng bào mòn cả sức khỏe lẫn tinh thần.",
        "order_index": 46,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q047",
        "section": "meaning_life",
        "text": "Mình tin không cần theo đuổi thứ gì quá lớn lao — biết đủ và an vui với hiện tại đã là hạnh phúc rồi.",
        "order_index": 47,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q048",
        "section": "emotions_conflict",
        "text": "Mình tránh những drama, xung đột căng thẳng — thà lui về một chút cho lòng mình được thanh thản.",
        "order_index": 48,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q049",
        "section": "work_discipline",
        "text": "Nghỉ ngơi, giải trí với mình không phải là lười biếng mà là một phần thiết yếu của cuộc sống tốt.",
        "order_index": 49,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },
    {
        "code": "q050",
        "section": "ethics_society",
        "text": "Mình nghĩ đời ngắn lắm, nên ưu tiên sống vui vẻ dễ chịu thay vì gồng mình theo những chuẩn mực khắt khe.",
        "order_index": 50,
        "illustration_key": "chill_cloud",
        "weights": {"epicureanism": 2},
    },

    # ---------- HIỆN SINH (existentialism) — q051..q060 ----------
    {
        "code": "q051",
        "section": "meaning_life",
        "text": "Cuộc đời không có sẵn ý nghĩa nào cả — chính mình là người tạo ra ý nghĩa cho nó bằng lựa chọn của mình.",
        "order_index": 51,
        "illustration_key": "meaning_void",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q052",
        "section": "work_discipline",
        "text": "Mình tin mình luôn có quyền lựa chọn, và mình chịu trách nhiệm hoàn toàn cho lựa chọn của mình.",
        "order_index": 52,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q053",
        "section": "ethics_society",
        "text": "Mình muốn tự quyết con đường đời mình, không sống theo khuôn mẫu mà gia đình hay xã hội đặt sẵn.",
        "order_index": 53,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q054",
        "section": "meaning_life",
        "text": "Mình sợ nhất là sống giả tạo theo kỳ vọng của người khác — mình muốn sống thật với chính mình.",
        "order_index": 54,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q055",
        "section": "emotions_conflict",
        "text": "Dù đời có phi lý, mình vẫn tự chọn dấn thân và tạo ra giá trị cho riêng mình.",
        "order_index": 55,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2, "absurdism": 1},
    },
    {
        "code": "q056",
        "section": "work_discipline",
        "text": "Mình không đổ lỗi hoàn cảnh — cuối cùng mình vẫn là người chọn cách phản ứng và bước tiếp.",
        "order_index": 56,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q057",
        "section": "meaning_life",
        "text": "Không ai định nghĩa được mình ngoài chính mình — mình là tổng của những gì mình đã chọn làm.",
        "order_index": 57,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q058",
        "section": "ethics_society",
        "text": "Mình tin mỗi người tự do tạo nên bản thân, nên mình tôn trọng cả những lựa chọn sống khác biệt của người khác.",
        "order_index": 58,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2, "humanism": 1},
    },
    {
        "code": "q059",
        "section": "emotions_conflict",
        "text": "Khi bế tắc, mình nhắc mình rằng mình luôn còn tự do để chọn một thái độ và một hướng đi mới.",
        "order_index": 59,
        "illustration_key": "cartoon_philosopher",
        "weights": {"existentialism": 2},
    },
    {
        "code": "q060",
        "section": "meaning_life",
        "text": "Mình thấy tự do tự tạo ý nghĩa cho đời mình là điều đáng sống nhất, dù nó đi kèm gánh nặng trách nhiệm.",
        "order_index": 60,
        "illustration_key": "meaning_void",
        "weights": {"existentialism": 2},
    },

    # ---------- HƯ VÔ (nihilism) — q061..q070 ----------
    {
        "code": "q061",
        "section": "meaning_life",
        "text": "Nói thật, mình nghĩ mọi thứ rồi cũng vô nghĩa như nhau, nên chẳng có gì đáng để xem là quan trọng tuyệt đối.",
        "order_index": 61,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q062",
        "section": "meaning_life",
        "text": "Những giá trị, chuẩn mực người ta tôn thờ, với mình chỉ là quy ước bịa ra, chẳng có gì thiêng liêng.",
        "order_index": 62,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q063",
        "section": "emotions_conflict",
        "text": "Nhiều lúc mình thấy cố gắng hay không cũng vậy thôi, vì kết cục rồi cũng chẳng khác biệt gì mấy.",
        "order_index": 63,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q064",
        "section": "work_discipline",
        "text": "Mình khó thấy lý do sâu xa nào để nỗ lực — phần lớn mục tiêu người ta đặt ra đều khá tùy tiện.",
        "order_index": 64,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q065",
        "section": "ethics_society",
        "text": "Mình không tin có một thước đo đúng-sai tối hậu nào, nên chẳng cái gì thật sự bắt buộc mình phải theo.",
        "order_index": 65,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q066",
        "section": "meaning_life",
        "text": "Mình nghĩ vũ trụ chẳng quan tâm gì đến con người, và cũng chẳng có sứ mệnh nào đang chờ mình cả.",
        "order_index": 66,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q067",
        "section": "emotions_conflict",
        "text": "Khi thất bại, mình hay tự nhủ 'thì cũng chẳng sao, có gì thực sự quan trọng đâu'.",
        "order_index": 67,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q068",
        "section": "work_discipline",
        "text": "Mình thấy mấy chuyện thành tích, danh vọng rốt cuộc khá rỗng tuếch, nên ít khi bận tâm theo đuổi.",
        "order_index": 68,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q069",
        "section": "meaning_life",
        "text": "Ý nghĩa cuộc sống ư? Mình nghĩ đó là câu hỏi không có đáp án, và có lẽ vốn cũng chẳng cần đáp án.",
        "order_index": 69,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },
    {
        "code": "q070",
        "section": "ethics_society",
        "text": "Mình hoài nghi mọi lý tưởng lớn lao — thường thì đằng sau chúng cũng trống rỗng cả thôi.",
        "order_index": 70,
        "illustration_key": "meaning_void",
        "weights": {"nihilism": 2},
    },

    # ---------- PHI LÝ (absurdism) — q071..q080 ----------
    {
        "code": "q071",
        "section": "meaning_life",
        "text": "Mình thấy đời chẳng có lý do rõ ràng nào cả, nhưng thế thì càng nên cứ sống cho đã, cho trọn vẹn.",
        "order_index": 71,
        "illustration_key": "meaning_void",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q072",
        "section": "emotions_conflict",
        "text": "Mình cười được trước những chuyện trớ trêu của cuộc đời, thay vì cay đắng hay gục ngã vì chúng.",
        "order_index": 72,
        "illustration_key": "cartoon_philosopher",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q073",
        "section": "work_discipline",
        "text": "Biết công việc nhiều khi vô nghĩa, mình vẫn làm nó hết mình như một trò chơi mà mình tự chọn.",
        "order_index": 73,
        "illustration_key": "deadline_monster",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q074",
        "section": "meaning_life",
        "text": "Mình chấp nhận rằng có thể mình chẳng bao giờ hiểu được 'tại sao', và vẫn thấy ổn với điều đó.",
        "order_index": 74,
        "illustration_key": "meaning_void",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q075",
        "section": "emotions_conflict",
        "text": "Mọi thứ rối ren, phi lý ư? Mình nhún vai rồi vẫn bước tiếp, chẳng cần đợi đời phải có nghĩa mới sống.",
        "order_index": 75,
        "illustration_key": "cartoon_philosopher",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q076",
        "section": "meaning_life",
        "text": "Với mình, chính việc sống hăng say giữa một thế giới vô lý mới là điều đáng nể nhất.",
        "order_index": 76,
        "illustration_key": "meaning_void",
        "weights": {"absurdism": 2, "existentialism": 1},
    },
    {
        "code": "q077",
        "section": "work_discipline",
        "text": "Mình kiểu Sisyphus vui vẻ: đẩy đá lên rồi lăn xuống hoài, nhưng mình vẫn tìm thấy niềm vui trong đó.",
        "order_index": 77,
        "illustration_key": "deadline_monster",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q078",
        "section": "ethics_society",
        "text": "Những quy tắc, nghi thức trịnh trọng của xã hội nhiều khi làm mình thấy buồn cười hơn là thiêng liêng.",
        "order_index": 78,
        "illustration_key": "cartoon_philosopher",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q079",
        "section": "emotions_conflict",
        "text": "Khi đời giáng cho một cú vô lý, mình chọn đối mặt bằng sự hài hước và lì lợm, chứ không gục ngã.",
        "order_index": 79,
        "illustration_key": "cartoon_philosopher",
        "weights": {"absurdism": 2},
    },
    {
        "code": "q080",
        "section": "meaning_life",
        "text": "Mình không cần đời phải có ý nghĩa lớn lao mới sống tốt — cứ sống trọn từng ngày là đủ với mình.",
        "order_index": 80,
        "illustration_key": "meaning_void",
        "weights": {"absurdism": 2},
    },

    # ---------- NHO GIA (confucian_ethics) — q081..q090 ----------
    {
        "code": "q081",
        "section": "ethics_society",
        "text": "Mình tin giữ đúng trên dưới, lễ phép với người lớn tuổi là nền tảng của một xã hội tử tế.",
        "order_index": 81,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q082",
        "section": "ethics_society",
        "text": "Bổn phận với gia đình, với cha mẹ là điều thiêng liêng, mình đặt nó lên trước cả sở thích cá nhân.",
        "order_index": 82,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q083",
        "section": "work_discipline",
        "text": "Mình coi trọng việc tu dưỡng bản thân mỗi ngày: sửa tính xấu, rèn đức, làm gương cho người khác.",
        "order_index": 83,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q084",
        "section": "meaning_life",
        "text": "Sống có ý nghĩa với mình là làm tròn vai của mình: con hiếu thảo, trò ngoan, người có trách nhiệm.",
        "order_index": 84,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q085",
        "section": "ethics_society",
        "text": "Mình tin mỗi người giữ đúng vị trí và bổn phận của mình thì xã hội mới hài hòa, ổn định.",
        "order_index": 85,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q086",
        "section": "emotions_conflict",
        "text": "Khi bất đồng với người trên, mình cố giữ lễ và ôn hòa, thay vì cãi tay đôi cho bằng được.",
        "order_index": 86,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q087",
        "section": "ethics_society",
        "text": "Mình trọng những nghi thức, truyền thống của gia đình, dòng họ — chúng gắn kết mọi người lại với nhau.",
        "order_index": 87,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q088",
        "section": "work_discipline",
        "text": "Mình tin làm việc gì cũng phải đàng hoàng, đúng mực, giữ chữ tín và danh dự của mình.",
        "order_index": 88,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q089",
        "section": "meaning_life",
        "text": "Mình muốn để lại tiếng thơm, sống sao cho gia đình, thầy cô có thể tự hào về mình.",
        "order_index": 89,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },
    {
        "code": "q090",
        "section": "emotions_conflict",
        "text": "Khi có mâu thuẫn, mình tin người có học nên biết nhường nhịn, giữ hòa khí và trật tự trên dưới.",
        "order_index": 90,
        "illustration_key": "society_pyramid",
        "weights": {"confucian_ethics": 2},
    },

    # ---------- VỊ LỢI (utilitarianism) — q091..q100 ----------
    {
        "code": "q091",
        "section": "ethics_society",
        "text": "Khi phải quyết định, mình chọn phương án mang lại lợi ích lớn nhất cho số đông, dù vài người phải chịu thiệt.",
        "order_index": 91,
        "illustration_key": "society_pyramid",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q092",
        "section": "ethics_society",
        "text": "Mình đánh giá đúng-sai bằng cách cân tổng lợi và tổng hại: cái nào lợi ròng cao hơn thì nên làm.",
        "order_index": 92,
        "illustration_key": "cartoon_philosopher",
        "weights": {"utilitarianism": 2, "pragmatism": 1},
    },
    {
        "code": "q093",
        "section": "work_discipline",
        "text": "Trong nhóm, mình sẵn sàng hy sinh lợi ích của một vài cá nhân để cả nhóm đạt kết quả tốt nhất.",
        "order_index": 93,
        "illustration_key": "deadline_monster",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q094",
        "section": "ethics_society",
        "text": "Mình nghĩ một quy định gây khó cho thiểu số nhưng có lợi cho đa số thì vẫn đáng để áp dụng.",
        "order_index": 94,
        "illustration_key": "society_pyramid",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q095",
        "section": "emotions_conflict",
        "text": "Khi giúp người, mình cân nhắc giúp sao cho tạo ra nhiều điều tốt nhất, chứ không chỉ chạy theo cảm xúc.",
        "order_index": 95,
        "illustration_key": "cartoon_philosopher",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q096",
        "section": "meaning_life",
        "text": "Với mình, một đời đáng sống là đời tạo ra tổng lượng hạnh phúc lớn nhất cho càng nhiều người càng tốt.",
        "order_index": 96,
        "illustration_key": "cartoon_philosopher",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q097",
        "section": "ethics_society",
        "text": "Mình tin đôi khi phải chấp nhận điều không dễ chịu với số ít để cứu hoặc mang lợi cho số đông.",
        "order_index": 97,
        "illustration_key": "society_pyramid",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q098",
        "section": "work_discipline",
        "text": "Nguồn lực có hạn thì nên rót vào chỗ tạo ra nhiều lợi ích nhất, dù vài chỗ khác phải chịu thiệt.",
        "order_index": 98,
        "illustration_key": "deadline_monster",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q099",
        "section": "emotions_conflict",
        "text": "Mình cố gạt cảm xúc cá nhân sang một bên để tính toán xem cái gì có lợi nhất cho cả tập thể.",
        "order_index": 99,
        "illustration_key": "cartoon_philosopher",
        "weights": {"utilitarianism": 2},
    },
    {
        "code": "q100",
        "section": "work_discipline",
        "text": "Mình thấy quyết định tốt là quyết định mà lợi ích cộng lại trừ đi thiệt hại cho ra con số lớn nhất.",
        "order_index": 100,
        "illustration_key": "deadline_monster",
        "weights": {"utilitarianism": 2},
    },

    # ---------- NHÂN VĂN (humanism) — q101..q110 ----------
    {
        "code": "q101",
        "section": "ethics_society",
        "text": "Với mình, không thể lấy lý do 'vì số đông' để chà đạp phẩm giá của một con người cụ thể.",
        "order_index": 101,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q102",
        "section": "ethics_society",
        "text": "Mình tin mỗi người đều có giá trị riêng, không thể quy ra con số hay đem ra đánh đổi được.",
        "order_index": 102,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q103",
        "section": "emotions_conflict",
        "text": "Trước một người đang khổ, mình quan tâm chính họ lúc này, chứ không ngồi cân đo họ 'đáng giúp' tới đâu.",
        "order_index": 103,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q104",
        "section": "ethics_society",
        "text": "Mình tin người mắc lỗi nên được cảm hóa, giáo dục để thay đổi, hơn là bị loại bỏ hay vứt đi.",
        "order_index": 104,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q105",
        "section": "meaning_life",
        "text": "Với mình, đời ý nghĩa là làm cho những người quanh mình được sống xứng đáng với phẩm giá con người.",
        "order_index": 105,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q106",
        "section": "work_discipline",
        "text": "Trong nhóm, mình không muốn bỏ rơi một thành viên yếu chỉ để cả nhóm chạy cho nhanh hơn.",
        "order_index": 106,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q107",
        "section": "ethics_society",
        "text": "Mình thấy một xã hội tốt là xã hội không bỏ lại ai phía sau, dù họ chỉ là thiểu số nhỏ bé.",
        "order_index": 107,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q108",
        "section": "emotions_conflict",
        "text": "Mình dễ đặt mình vào hoàn cảnh người khác, nên thấy khó lòng đem hy sinh ai đó cho 'cái lợi chung'.",
        "order_index": 108,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q109",
        "section": "meaning_life",
        "text": "Mình tin con người, với tất cả cảm xúc và phẩm giá của họ, mới là điều đáng trân trọng nhất.",
        "order_index": 109,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },
    {
        "code": "q110",
        "section": "work_discipline",
        "text": "Mình muốn đối xử với đồng đội như những con người, chứ không phải như công cụ để đạt chỉ tiêu.",
        "order_index": 110,
        "illustration_key": "cartoon_philosopher",
        "weights": {"humanism": 2},
    },

]
